language: julia
os:
  - linux
  - osx
julia:
  - 1
  - nightly

matrix:
  allow_failures:
    - julia: nightly

jobs:
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TRAVIS_DOCS   # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  local_dir: docs/build
  target_branch: gh-pages