language: julia

os:
  - osx
  - linux

julia:
  - 1.0
  - 1.3
  - 1.4
  - nightly

notifications:
  email: false

jobs:
  allow_failures:
   - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - julia --project=. -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=. docs/make.jl
      after_success: skip
